apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app.py
  template:
    metadata:
      labels:
        app: app.py
    spec:
      containers:
        - name: app.py
          image:
          ports:
            - containerPort: 5000