apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: app.py
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort
  